### PR TITLE
Use Amber Web Authorization for login

### PR DESCRIPTION
**Pull request by vige**

### CODE REVIEW

**Comment by poetaster** [comment]
Thanks a bunch for the support!

**Comment by poetaster** [comment]
Two observations, one of which is just the way it is, the other ...
1. It remains impossible to get a user context for qmllive debugging. probably remains problematic
2. I failed to get a login screen with the jolla browser. using angelfish worked. 

Question, you surely tested with the jolla browser?

**Comment by poetaster** [comment]
On 2, looks like it's fine on the 10 III but something is odd (well, something is odd) with the Volla22/GS5 ... It also works fine with the original Volla phone (GS290).

**Comment by vige** [comment]
> On 2, looks like it's fine on the 10 III but something is odd (well, something is odd) with the Volla22/GS5 ... It also works fine with the original Volla phone (GS290).

That indeed sounds odd. I tested on 10 III and the emulator.

> It remains impossible to get a user context for qmllive debugging. probably remains problematic

I didn't try qmllive this time, but regular qml debugger worked fine.

**Comment by poetaster** [comment]
Yeah, it's something odd with the kernels in the Mimameid releases. I've tested it after rebooting and on a second phone, and it's fine. If errors occur for users, I know how to respond. I'm packaging up and will release this week. Thanks again for all your efforts!

**Pull request merged**
